Repository haskell/alex, pull requests merged in 2023-05, with the labels that each got.

#237 Remove old pregenerated lexer
  src/Scan.hs
Labels: build / install

#238 Simplified test suite that runs on Windows and MacOS
  .github/workflows/haskell-ci-simple.yml
Labels: continuous integration (CI)

#234 Add a stock Ord instance for AlexPosn
  .gitignore
  CHANGELOG.md
  alex.cabal
  data/AlexWrappers.hs
  src/ParseMonad.hs
  tests/tokens_monad_bytestring.x
Labels: wrapper

#239 v3.3.0.0: Switch to four-digit version numbers
  CHANGELOG.md
  alex.cabal
Labels: re: versioning
